import type { Metadata, Viewport } from "next";
import { cn, ThemeProvider } from "@/lib";
import { GoogleTagManager, GoogleAnalytics } from "@next/third-parties/google";
import { Toaster } from "sonner";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Header } from "@/components/reusables";
import { HeroUIProviderWrapper } from "@/components/providers/hero-ui-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	themeColor: "#000000",
	width: "device-width",
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			className="m-0 p-0 h-full">
			<body className={cn("min-h-screen bg-black text-white scroll-smooth antialiased m-0 p-0 h-full")}>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem
					disableTransitionOnChange>
					<HeroUIProviderWrapper>
						<NextTopLoader
							color="#000000"
							showSpinner={false}
							easing="ease"
						/>
						<Header />
						<main className="w-full">
							{children}
						</main>

						<Toaster
							position="top-right"
							expand={true}
							richColors
							closeButton
							toastOptions={{
								classNames: {
									toast: "bg-black/90 backdrop-blur-xl border border-white/10 shadow-2xl",
									title: "text-white font-semibold",
									description: "text-gray-300",
									actionButton: "bg-white/10 hover:bg-white/20 text-white",
									cancelButton: "bg-white/5 hover:bg-white/10 text-gray-300",
									success: "border-green-500/50",
									error: "border-red-500/50",
									warning: "border-yellow-500/50",
									info: "border-blue-500/50",
								},
								duration: 4000,
							}}
						/>
						{process.env.NEXT_PUBLIC_GA_ID && <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID} />}
						{process.env.NEXT_PUBLIC_GTM_ID && <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_ID} />}
					</HeroUIProviderWrapper>
				</ThemeProvider>
			</body>
		</html>
	);
}
